### ISSUE TITLE
'locahost' typo

### ISSUE THREAD

**Issue by jloomisVCE** [living-atlases/generator-living-atlas#8]
File: https://github.com/living-atlases/generator-living-atlas/blob/master/generators/app/templates/quick-start-local-extras.ini

I think 'locahost' is a typo:
https://github.com/living-atlases/generator-living-atlas/blob/9c6244834868fe654b7954fb2c674d3e54288308/generators/app/templates/quick-start-local-extras.ini#L31

https://github.com/living-atlases/generator-living-atlas/blob/9c6244834868fe654b7954fb2c674d3e54288308/generators/app/templates/quick-start-local-extras.ini#L34

**Comment by vjrj** [comment]
Yes, it is :-D

**Comment by vjrj** [comment]
Thanks indeed @jloomisVCE , see our [changelog](https://github.com/living-atlases/generator-living-atlas/blob/master/CHANGELOG.md) for details.
