### ISSUE TITLE
add vars for api keys

### ISSUE THREAD

**Issue by jloomisVCE** [living-atlases/generator-living-atlas#9]
@vjrj I started a Github 'discussion' here: https://github.com/VtEcostudies/generator-living-atlas/discussions/1

https://github.com/living-atlases/generator-living-atlas/blob/master/generators/app/templates/quick-start-local-extras.ini

#Setting up api keys is confusing
#Some api key variables are missing from local-extras.ini
#Maybe add some helpful hints on how to set these up

**Comment by vjrj** [comment]
More discussion here https://github.com/VtEcostudies/generator-living-atlas/discussions/1

**Comment by vjrj** [comment]
I've released a new version with some api_keys added and links to documentation. You can test it in your inventories with:

```
npm install -g generator-living-atlas
yo living-atlas --replay-dont-ask 
```

that with generate a new `.sample` with this info.

**Comment by vjrj** [comment]
I forget to mention that I did add all to [all:vars] because this simplifies the generator code.

**Comment by vjrj** [comment]
FYI, I'm trying to create some role to add this automatically. The goal is to generate & configure the keys and add it the apikeys db.

**Comment by vjrj** [comment]
WIP: https://github.com/AtlasOfLivingAustralia/ala-install/pull/461

**Comment by vjrj** [comment]
Closing this as now ala-install auto-add keys with 461 and https://github.com/AtlasOfLivingAustralia/ala-install/pull/462
Thanks @jloomisVCE
